FROM almalinux:9
ADD https://raw.githubusercontent.com/daws-78s/expenses-documention/refs/heads/main/mysql.MD /tmp/mysql.txt
ADD sample-1.tar /tmp/
CMD ["sleep", "60"]

#ADD instruction will download the content from internet into the image and untart the files into the images